//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orderprods = new HashSet<Orderprod>();
        }
    
        public string oid { get; set; }
        public System.DateTime odate { get; set; }
        public Nullable<System.DateTime> delidate { get; set; }
        public string paidmethod { get; set; }
        public string agentname { get; set; }
        public string agentphone { get; set; }
        public string agentaddress { get; set; }
        public Nullable<int> paymentstt { get; set; }
        public string orderstt { get; set; }
        public Nullable<int> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderprod> Orderprods { get; set; }
    }
}
